### ISSUE TITLE
Make a greater ReadMe 

### ISSUE THREAD

**Issue by Ailelame** [newatox/formation#2]
Hey, after "Repository for educational purpose. Created by Arnaud Ringenbach"
Could you make a carriage return between those 2

**Comment by Ailelame** [comment]
Attends, je vais faire une nouvelle branche et te proposer quelque chose

**Comment by Ailelame** [comment]
C'est bon, regardes mon last commit 1cd36d807e615de0bdb9a02592685a3867332688

**Comment by newatox** [comment]
:)

**Comment by newatox** [comment]
#3

**Comment by Ailelame** [comment]
Merci
