### ISSUE TITLE
Where are the fu***** poney?!

### ISSUE THREAD

**Issue by Ailelame** [newatox/formation#4]
Ya talking about making a poney project and you ain't got any horses...
Add a picture man!

**Comment by Ailelame** [comment]
This one ! [https://www.google.fr/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiKsvHLzdvWAhUBnRoKHfG7BhoQjRwIBw&url=http%3A%2F%2Fblog-mastere2-rp-events.ecs-paris.com%2Fgeneral%2Fle-poney-wonder-baby-sitter&psig=AOvVaw2DGu0vwYasSSUZRWPe4WfG&ust=1507365869628061](url)
Go poney GO !

**Comment by newatox** [comment]
I'm on it.

**Comment by Ailelame** [comment]
Ah le bon lien : http://blog-mastere2-rp-events.ecs-paris.com/wp-content/uploads/2014/04/poney-rose.jpg

**Comment by Ailelame** [comment]
+1
